---
################################################################################
#
# Title:        add_esxi_dvs_vmk.yml
# Author:       Olli Walsdorf
# Date:         2022-02-11
# Description:  Add vMotion VMkernel to DVS
#
# Variables:    vcenter_hostname = FQDN or IP of vCenter
#               vcenter_username = vCenter username
#               vcenter_password = vCenter password
#               dvs_name = Name of DVS switch
#               dvs_vmk_list = List of network parameter to be used
#
# Modules:      vmware_vmkernel
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html#plugins-in-community-vmware
#
################################################################################

- name: Create vMotion VMKernel
  community.vmware.vmware_vmkernel:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ inventory_hostname }}'
    dvswitch_name: '{{ dvs_name }}'
    portgroup_name: '{{ item.portgroup_vmotion }}'
    # MTU value is hardcoded to 9000 for better performance
    mtu: 9000
    network:
      type: 'static'
      ip_address: '{{ item.ip_vmotion }}'
      subnet_mask: '{{ item.netmask }}'
      tcpip_stack: '{{ item.stack_vmotion }}'
    state: present
  delegate_to: localhost
