---
################################################################################
#
# Title:        create_cluster.yml
# Author:       Olli Walsdorf
# Date:         2022-02-09
# Description:  Create Cluster under vCenter
#
# Variables:    vcenter_hostname = FQDN or IP of vCenter
#               vcenter_username = vCenter username
#               vcenter_password = vCenter password
#               vcenter_dc = vCenter datacenter name
#               vcenter_cluster = vCenter cluster name
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/community/vmware/index.html#plugins-in-community-vmware
#
################################################################################

- name: VMware Cluster - Setup
  community.vmware.vmware_cluster:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    validate_certs: no
    datacenter_name: '{{ vcenter_dc }}'
    cluster_name: '{{ vcenter_cluster }}'

- name: VMware Cluster - Enable DRS
  community.vmware.vmware_cluster_drs:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter_name: "{{ vcenter_dc }}"
    cluster_name: "{{ vcenter_cluster }}"
    enable_drs: yes

- name: VMware Cluster - Enable HA
  community.vmware.vmware_cluster_ha:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    datacenter_name: "{{ vcenter_dc }}"
    cluster_name: "{{ vcenter_cluster }}"
    enable_ha: yes
