---
################################################################################
#
# Title:        update_esxi.yml
# Author:       Olli Walsdorf
# Date:         2021-11-28
# Description:  Add NFS Datastore to each ESXi host
#
# Variables:
#
#
# URLs:         https://galaxy.ansible.com/community/vmware
#
# Built-in help:
# ansible-doc
#
################################################################################
#
#- hosts: localhost
#  connection: local
#  collections:
#  - community.vmware
#  gather_facts: false
#  tasks:

- name: Download nenic driver
  command: wget {{ nenic_offline_bundle_url }} -P /tmp
  args:
    warn: false

- name: Update nenic driver
  command: esxcli software component apply -d /tmp/{{ nenic_filename }}
  args:
    warn: false

- name: Reboot Host
  command: reboot
  args:
    warn: false
