---
################################################################################
#
# Title:        chassis_profile_deploy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Deploy Chassis Profile in Intersight
#
# Modules:      chassis/Profiles
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Get Chassis Profile List"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /chassis/Profiles
    query_params:
      $filter: "AssignedChassis.Moid eq '{{ inventory_list.chassis_moid }}'"
  register: chassis_profile_resp

- name: "Deploy Chassis Profile"
  intersight_rest_api:
    <<: *api_info
    resource_path: /chassis/Profiles
    query_params:
      $filter: "Name eq 'CP-{{ inventory_hostname }}'"
    api_body: {
      "Action": "Deploy",
    }
  when:
    - chassis_profile_resp.api_response.AssignedChassis.Moid is defined
  delegate_to: localhost
  tags: chassis_profiles
