---
################################################################################
#
# Title:        gather_moids.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Gather Chassis MOID and write to temp file
#
# Modules:      /equipment/Chasses
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: Delete existing variable file
  file:
    path: "{{ filepath_chassis }}"
    state: absent
  run_once: true
  no_log: true

- name: Gather Chassis Moid
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
    host_group: Intersight_Chassis
  block:
    - intersight_rest_api:
        <<: *api_info
        resource_path: /equipment/Chasses
        query_params:
          $filter: "Name eq '{{ inventory_hostname }}'"
      register: chassis
    - lineinfile:
        path: "{{ filepath_chassis }}"
        line: "inventory_list:"
        state: present
        create: true
    - lineinfile:
        path: "{{ filepath_chassis }}"
        insertafter: EOF
        line: "  name: {{ chassis.api_response.Name }}"
        state: present
        create: true
    - lineinfile:
        path: "{{ filepath_chassis }}"
        insertafter: EOF
        line: "  chassis_moid: {{ chassis.api_response.Moid }}"
        state: present
        create: true
