---
################################################################################
#
# Title:        imc_access.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure IMC Access in Intersight
#
# Variables:    imc_access_name = Name of IMC access policy
#               imc_access_vlan = VLAN for IMC access
#
# Modules:      access/Policies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure IMC Access"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /access/Policies
    query_params:
      $filter: "Name eq '{{ imc_access_name }}'"
    api_body: {
      "Name": "{{ imc_access_name }}",
      "AddressType": {
          "EnableIpV4": true,
          "EnableIpV6": false
      },
      "InbandIpPool": {
          "Moid": "{{ ip_pool_resp.api_response.Moid }}"
      },
      "InbandVlan": "{{ imc_access_vlan }}",
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  tags: imc_access
  register: imc_access_resp
  run_once: true
  delegate_to: localhost
