---
################################################################################
#
# Title:        ip_pool.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure IP Pool in Intersight
#
# Variables:    ip_pool_name = Name of the IP pool
#               ip_pool_block_from = IP starting address
#               ip_pool_block_size = Size of IP pool
#               ip_pool_config_gateway = Gateway of IP pool
#               ip_pool_config_netmask = Netmask of IP pool
#               ip_pool_config_dns1 = Primary DNS of IP pool
#               ip_pool_config_dns2 = Secondary DNS of IP pool
#
# Modules:      ippool/Pools
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure IP Pool"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /ippool/Pools
    query_params:
      $filter: "Name eq '{{ ip_pool_name }}'"
    api_body: {
      "Name": "{{ ip_pool_name }}",
      "AssignmentOrder": "default",
      "IpV4Blocks": [{
          "From": "{{ ip_pool_block_from }}",
          "Size": "{{ ip_pool_block_size }}"
      }],
      "IpV4Config": {
          "Gateway": "{{ ip_pool_config_gateway }}",
          "Netmask": "{{ ip_pool_config_netmask }}",
          "PrimaryDns": "{{ ip_pool_config_dns1 }}",
          "SecondaryDns": "{{ip_pool_config_dns2 }}"
      },
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }

  tags: ip_pool
  register: ip_pool_resp
  run_once: true
  delegate_to: localhost
