---
################################################################################
#
# Title:        main.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
#
# Description:  Role for setting up UCS X-Series Chassis in Intersight
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

# Get the Organization Moid used by all profiles and policies
- name: "Get Organization {{ ucs_org }} Moid"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ ucs_org }}'"
  register: org_resp
  delegate_to: localhost
  tags: always
  run_once: true

# Setup UUID Pool
- include: uuid_pool.yml

# Setup MAC Pool
- include: mac_pool.yml

# Setup IP Pool
- include: ip_pool.yml

# Setup IMC Access
- include: imc_access.yml

# Setup Power Policy
- include: power_policy.yml

# Gather Moids for Profiles
- include: gather_moids.yml

# Create/Update Chassis Profile
- include: chassis_profile_assign.yml

# Wait for Chassis Profiles getting assigned
- name: Wait for Chassis Profile assignment
  pause:
    minutes: 1
  when: configure_ucs_chassis == 'true'

# Deploy Chassis Profile
- include: chassis_profile_deploy.yml

# Wait for Chassis Profiles getting deployed
- name: Wait for Chassis Profile deployment
  pause:
    minutes: 1
  when: configure_ucs_chassis == 'true'
