---
################################################################################
#
# Title:        power_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure Power Policy in Intersight
#
# Variables:    power_policy_name = Name of the Power policy
#               power_policy_profiling = Profiling state
#               power_policy_restore = Restore state
#               power_policy_redundancy = Redundancy of the power supplies
#               power_policy_allocation = Allocation of power
#
# Modules:      power/Policies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure Power Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /power/Policies
    query_params:
      $filter: "Name eq '{{ power_policy_name }}'"
    api_body: {
      "Name": "{{ power_policy_name }}",
      "AllocatedBudget": "{{ power_policy_allocation }}",
      "PowerProfiling": "{{ power_policy_profiling }}",
      "PowerRestoreState": "{{ power_policy_restore }}",
      "RedundancyMode": "{{ power_policy_redundancy }}",
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  tags: power_policy
  register: power_policy_resp
  run_once: true
  delegate_to: localhost
