---
################################################################################
#
# Title:        uuid_pool.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure UUID Pool in Intersight
#
# Variables:    uuid_pool_name = Name of the UUID pool
#               uuid_prefix = Prefix of UUID
#               uuid_size = Size of the pool
#               uuid_from = Starting point of the pool
#
# Modules:      uuidpool/Pools
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure UUID Pool"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /uuidpool/Pools
    query_params:
      $filter: "Name eq '{{ uuid_pool_name }}'"
    api_body: {
      "Name": "{{ uuid_pool_name }}",
      "AssignmentOrder": "default",
      "Prefix": "{{ uuid_prefix }}",
      "UuidSuffixBlocks": [
        {
            "From": "{{ uuid_from }}",
            "Size": "{{ uuid_size }}"
        }
      ],
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }

  tags: uuid_pool
  register: uuid_pool_resp
  run_once: true
  delegate_to: localhost
