---
################################################################################
#
# Title:        eth_network_group_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure Ethernet Network Group Policy in Intersight
#
# Variables:    eth_network_group_list = List of VLANs to create
#
# Modules:      fabric/EthNetworkGroupPolicies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure Ethernet Network (VLAN) Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    api_body: {
      "Name": "{{ item.name }}",
      "VlanSettings": {
        "AllowedVlans": "{{ item.vlan_number_allowed }}",
        "NativeVlan": "{{ item.vlan_number_native }}"
      },
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ eth_network_group_list }}"
  when: eth_network_group_list is defined
  register: eth_network_group_resp
  tags: network
  run_once: true
  delegate_to: localhost
