---
################################################################################
#
# Title:        eth_adapter_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure Ethernet Adapter Policy in Intersight
#
# Variables:    eth_adapter_config_name = Name of Ethernet adapter policy
#               eth_adapter_config_slot = Slot of Ethernet adapter
#               eth_adapter_config_fec_mode = FEC mode for physical VIC port
#
# Modules:      adapter/ConfigPolicies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure Ethernet Adapter Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /adapter/ConfigPolicies
    query_params:
      $filter: "Name eq '{{ eth_adapter_config_name }}'"
    api_body: {
      "Name": "{{ eth_adapter_config_name }}",
      "Settings":[
        {
          "SlotId": "{{ eth_adapter_config_slot }}",
          "EthSettings":{
            "LldpEnabled":true
          },
          "FcSettings":{
            "FipEnabled":false
          },
          "PortChannelSettings":{
            "Enabled": true
          },
          "DceInterfaceSettings": [
            {
              "FecMode": "{{ eth_adapter_config_fec_mode }}",
              "InterfaceId": 0
            },
            {
              "FecMode": "{{ eth_adapter_config_fec_mode }}",
              "InterfaceId": 1
            },
            {
              "FecMode": "{{ eth_adapter_config_fec_mode }}",
              "InterfaceId": 2
            },
            {
              "FecMode": "{{ eth_adapter_config_fec_mode }}",
              "InterfaceId": 3
            }
          ]
        }
      ],
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  tags: network
  register: eth_adapter_resp
  run_once: true
  delegate_to: localhost
  no_log: true
