---
################################################################################
#
# Title:        qos_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure QoS Policies in Intersight
#
# Variables:    qos_policy_list = List of QoS policies to create
#
# Modules:      vnic/EthQosPolicies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure Ethernet QoS Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthQosPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    api_body: {
      "Name": "{{ item.name }}",
      "Mtu": "{{ item.mtu }}",
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ qos_policy_list }}"
  when: qos_policy_list is defined
  register: eth_qos_resp
  tags: network
  run_once: true
  delegate_to: localhost
  no_log: true
