---
################################################################################
#
# Title:        server_profile_assign_ceph.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Create Server Profiles for Ceph and assign to Blades
#
# Modules:      server/Profiles
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: Include vars file
  include_vars: "{{ filepath_server }}"
  run_once: true

- name: "Configure Server Profiles for Ceph Blades"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq 'SP-{{ item.name }}'"
    api_body: {
      "Action": "No-op",
      "Name": "SP-{{ item.name }}",
      "AssignedServer": {
        "Moid": "{{ item.server_moid }}",
        "ObjectType": "compute.Blade"
      },
      "PolicyBucket": [
        {
          "Moid": "{{ boot_policy_resp.api_response.Moid }}",
          "ObjectType": "boot.PrecisionPolicy"
        },
        {
          "Moid": "{{ imc.api_response.Moid }}",
          "ObjectType": "access.Policy"
        },
        {
          "Moid": "{{ storage_policy_resp.api_response.Moid }}",
          "ObjectType": "storage.StoragePolicy"
        },
        {
          "Moid": "{{ item.vmedia_moid }}",
          "ObjectType": "vmedia.Policy"
        },
        {
          "Moid": "{{ lan_connectivity_resp.results.0.api_response.Moid }}",
          "ObjectType": "vnic.LanConnectivityPolicy"
        }
      ],
      "UuidPool": {
        "Moid": "{{ uuid.api_response.Moid }}"
      },
      "TargetPlatform": "FIAttached",
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  register: server_profile_ceph_resp
  when:
    - "'Intersight_Blades_Ceph' in group_names"
    - inventory_list_ceph is defined
    - configure_ucs_ceph == 'true'
  delegate_to: localhost
  tags: server_profiles
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ inventory_list_ceph }}"
  run_once: true
