---
################################################################################
#
# Title:        server_profile_deploy_ocp.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Deploy Server Profiles for OCP Blades
#
# Modules:      server/Profiles
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Deploy Server Profiles for OCP Blades"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq 'SP-{{ inventory_hostname }}'"
    api_body: {
      "Action": "Deploy",
    }
  when:
    - "'Intersight_Blades_OCP' in group_names"
    - configure_ucs_ocp == 'true'
  delegate_to: localhost
  tags: server_profiles
