---
################################################################################
#
# Title:        server_poweron.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Power On Server and boot from CIMC_vMedia
#
# Variables:    power_device = Media to boot from
#
# Modules:      compute/ServerSettings
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Power On Ceph Blades"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /compute/ServerSettings
    query_params:
      $filter: "Name eq '{{ inventory_hostname }}'"
    api_body: {
      "AdminPowerState": "PowerCycle",
      "OneTimeBootDevice": "{{ power_device }}"
    }
  delegate_to: localhost
  tags: server_profiles
  when:
    - configure_ucs_ceph == 'true'
    - "'Intersight_Blades_Ceph' in group_names"

- name: "Power On OCP Blades"
  intersight_rest_api:
    <<: *api_info
    resource_path: /compute/ServerSettings
    query_params:
      $filter: "Name eq '{{ inventory_hostname }}'"
    api_body: {
      "AdminPowerState": "PowerCycle",
      "OneTimeBootDevice": "{{ power_device }}"
    }
  delegate_to: localhost
  tags: server_profiles
  when:
    - configure_ucs_ocp == 'true'
    - "'Intersight_Blades_OCP' in group_names"
