################################################################################
#
# Title:        vmedia_ocp_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure vMedia Policy for OCP Blades and gather vMedia and
#               server MOID and write it into a temp file
#
# Variables:    vmedia_ocp_list = List of vMedia policies
#
# Modules:      vmedia/Policies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure vMedia Policy for OCP Blade"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vmedia/Policies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    api_body: {
      "Name": "{{ item.name }}",
      "Enabled": true,
      "Encryption": true,
      "LowPowerUsb": false,
      "Mappings": [
        {
          "MountProtocol": "{{ item.vmedia_mount_proto }}",
          "FileLocation": "{{ item.vmedia_file_name }}",
          "VolumeName": "{{ item.vmedia_volume_name }}",
          "DeviceType": "{{ item.vmedia_device }}"
        }
      ],
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  register: vmedia_ocp_policy_resp
  tags: virtual_media
  delegate_to: localhost

- name: Gather vMedia Moid
  vars:
    host_group: Intersight_Blades_OCP
  block:
    - cisco.intersight.intersight_rest_api:
        <<: *api_info
        resource_path: /compute/PhysicalSummaries
        query_params:
          $filter: "Name eq '{{ item.vmedia_server }}'"
      register: server_ocp
    - lineinfile:
        path: "{{ filepath_server }}"
        line: "inventory_list_ocp:"
        state: present
        create: true
    - lineinfile:
        path: "{{ filepath_server }}"
        insertafter: EOF
        line: "  - name: '{{ server_ocp.api_response.Name }}'"
        state: present
        create: true
    - lineinfile:
        path: "{{ filepath_server }}"
        insertafter: EOF
        line: "    server_moid: '{{ server_ocp.api_response.Moid }}'"
        state: present
        create: true
    - lineinfile:
        path: "{{ filepath_server }}"
        insertafter: EOF
        line: "    vmedia_moid: '{{ vmedia_ocp_policy_resp.api_response.Moid }}'"
        state: present
        create: true
  when:
    - vmedia_ocp_policy_resp is defined
