---
################################################################################
#
# Title:        vnic_adapter_policy.yml
# Author:       Olli Walsdorf
# Date:         2022-02-08
# Description:  Configure vNIC Adapter Policy in Intersight
#
# Variables:    vnic_adapter_list = List of vNIC Adapter Policies to create
#
# Modules:      vnic/EthAdapterPolicies
#
# URLs:         https://docs.ansible.com/ansible/latest/collections/cisco/intersight/index.html
#
################################################################################

- name: "Configure vNIC Adapter Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthAdapterPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    api_body: {
      "Name": "{{ item.name }}",
      "InterruptSettings": {
        "Count": "{{ item.interrupt }}",
        "Mode": "MSIx",
        "CoalescingTime": 125,
        "CoalescingType": "MIN"
      },
      "RxQueueSettings": {
        "Count": "{{ item.rxqueue }}",
        "RingSize": "{{ item.rxring }}"
      },
      "TxQueueSettings": {
        "Count": "{{ item.txqueue }}",
        "RingSize": "{{ item.txring }}"
      },
      "CompletionQueueSettings": {
        "Count": "{{ item.compqueue }}"
      },
      "TcpOffloadSettings": {
        "LargeReceive": "{{ item.large_receive }}",
        "LargeSend": "{{ item.large_send }}"
      },
      "RssSettings": "{{ item.rss }}",
      "Organization": {
        "Moid": "{{ org_resp.api_response.Moid }}"
      }
    }
  loop_control:
    label: "{{ item.name }}"
  loop: "{{ vnic_adapter_list }}"
  when: vnic_adapter_list is defined
  register: vnic_adapter_resp
  tags: lan_connectivity
  run_once: true
  delegate_to: localhost
