---
- set_fact: Get Login
  vars:
    api_info: &api_info
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  run_once: true

- name: Gather Server Profile Name
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq 'SP-{{ inventory_hostname }}'"
  register: server_profile
  when:
    - "'Intersight_Blades' in group_names"


- name: Unassign Profiles
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq 'SP-{{ inventory_hostname }}'"
    api_body: {
      "Action": "Unassign",
    }
  when:
    - "'Intersight_Blades' in group_names"

- name: Wait for Unassignment
  pause:
    minutes: 5

- name: Remove Profiles
  intersight_rest_api:
    <<: *api_info
    resource_path: /server/Profiles
    query_params:
      $filter: "Name eq 'SP-{{ inventory_hostname }}'"
    state: absent
  when:
    - "'Intersight_Blades' in group_names"


- name: Delete LAN Connectivity
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/LanConnectivityPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ lan_connectivity_list }}"
  run_once: true

- name: Delete Ethernet vNIC Interface Ceph
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthIfs
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ ceph_vnic_list }}"
  run_once: true

- name: Delete Ethernet vNIC Interface OCP
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthIfs
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ ocp_vnic_list }}"
  run_once: true

- name: Delete vMedia Policy Ceph
  intersight_rest_api:
    <<: *api_info
    resource_path: /vmedia/Policies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ vmedia_ceph_list }}"
  run_once: true

- name: Delete vMedia Policy OCP
  intersight_rest_api:
    <<: *api_info
    resource_path: /vmedia/Policies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ vmedia_ocp_list }}"
  run_once: true

- name: Delete Boot Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /boot/PrecisionPolicies
    query_params:
      $filter: "Name eq '{{ boot_policy_name }}'"
    state: absent
  run_once: true

- name: Delete Storage Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /storage/StoragePolicies
    query_params:
      $filter: "Name eq '{{ storage_policy_name }}'"
    state: absent
  run_once: true

- name: Delete vNIC Adapter Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthAdapterPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ vnic_adapter_list }}"
  run_once: true

- name: Delete Ethernet Network (VLAN) Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /fabric/EthNetworkGroupPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ eth_network_group_list }}"
  run_once: true

- name: Delete Ethernet Network Control Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /fabric/EthNetworkControlPolicies
    query_params:
      $filter: "Name eq '{{ eth_network_control_name }}'"
    state: absent
  run_once: true

- name: Delete Ethernet Adapter Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /adapter/ConfigPolicies
    query_params:
      $filter: "Name eq '{{ eth_adapter_config_name }}'"
    state: absent
  run_once: true

- name: Delete Ethernet QoS Policy
  intersight_rest_api:
    <<: *api_info
    resource_path: /vnic/EthQosPolicies
    query_params:
      $filter: "Name eq '{{ item.name }}'"
    state: absent
  loop: "{{ qos_policy_list }}"
  run_once: true
